# -*- coding: utf-8 -*-
"""gerador de senhas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/196F31itpqtd3hlwcALJyhEOEDDixfkY-

TESTE DE GERADOR DE SENHAS
"""

# para gerar números aleatórios
import random
# caracteres para utilizar na senha
caracteres = "abcdesghijklmnopqrstuvwxyz1234567890"
# tamanho da senha
tamanho = int(input("Digite o tamanho da senha: "))

# armazenar a senha
senha = []
# loop que escolha a senha
for i in range(tamanho):
  # caractere aleatório
  caractere = random.choice(caracteres)
  senha.append(caractere)

# lista em string
senha = "".join(senha)

print("A senha gerada é: ", senha)